### ISSUE TITLE
configuration of linguistic processors

### ISSUE THREAD

**Issue by jiskattema** [cltl/NAF-4-Development#2]
What is the recommended way to add more metadata on a liguistic processor?

The following information would be useful to store in the <lp> element:
* we have retrained stanza to do dependency parsing, so we would like to specify the specific model used.
* command line options to exactly reproduce the process

**Comment by sarnoult** [comment]
Version 3.3 allows to provide more information about linguistic processors. 

- Each lp element notably allows lpDependency children, providing information about the type (model, data, etc), name and version of a linguistic-processor dependency. 
- lp elements can also be attributed an id, which can be used to uniquely identify a processing step.

See the lp element for 'entities' in this [example](https://github.com/cltl/NAF-4-Development/blob/master/examples/v33/lpdep.naf).

There is currently no provision for command-line options. Command-line options can have a lot of hidden dependencies, so I doubt that providing them will guarantee exact reproduction.
