### ISSUE TITLE
document metadata

### ISSUE THREAD

**Issue by jiskattema** [cltl/NAF-4-Development#4]
What is the recommended way to store document metadata in NAF?
For instance the file name and/or URI of the document being processed.

Also interesting could be author, publication date, creation date, etc.

**Comment by sarnoult** [comment]
The NAF header has two elements for this: _fileDesc_ and _public_: 
- _fileDesc_ provides metadata about the naf document itself (filename, creation date, etc.)
- _public_ provides public information about the document, like an URI. The information provided there is minimal indeed, and publication date for instance is not supported.

The attributes for these elements can be found in the [DTD](https://github.com/cltl/NAF-4-Development/blob/master/resources/dtd/naf_v3.3.dtd)
