### ISSUE TITLE
annotation schema used for pos, semRole, morphofeat, rfunc

### ISSUE THREAD

**Issue by jiskattema** [cltl/NAF-4-Development#5]
It is unclear how to indicate the schema used for various annotations, or what is the default schema.

For part-of-speech, the document lists the valid options, but these dont correspond to the ones used in the Newsreader pipeline.

For semRole, the NAF document only suggests using 'A0', 'A1', when the role corresponds to a PropBank predicate. but that is not specific enough. It is also unclear what to do if it is *not* a PropBank predicate.

For a term's morphofeat, there is no further mention of allowed values / content. The newsreader pipeline assumes it follows 'POS(A,B)' format where POS is a part-of-speech tag as produced by Alpino, and (A,B) are similarly from Alpino output.

For dependencies, there is the rfunc attribute. There is a (non exhaustive) list of values, but no way to indicate if these are from Universal Depencendies, or Alpino

**Comment by sarnoult** [comment]
The [NAF Newsreader documentation](https://raw.githubusercontent.com/newsreader/NAF/master/naf.pdf) must be understood in the context of the Newsreader project. For a project-free specification, it is perhaps best to directly look at the [DTD](https://github.com/cltl/NAF-4-Development/blob/master/resources/dtd/naf_v3.3.dtd).

Within Newsreader, POS tagging and parsing were performed with Alpino. If the DTD does not allow to represent information from Universal Dependencies, we can adapt it.
Naf is currently being used for FrameNet annotations, so there is no restriction to PropBank.
